FROM debian:jessie
MAINTAINER technology@vikingco.com

# Prepare pyenv
ENV PYENV_ROOT $HOME/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH
ENV PYTHON_VERSIONS {{ pythonversions }}

# Install base requirements
RUN set -x \
    && buildDeps=' \
        ca-certificates \
        make \
        build-essential \
        zlib1g-dev \
        libbz2-dev \
        libssl-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        git-core \
    ' \
    && deps=' \
        openssl \
    ' \
    && requiredPipPackages=' \
        ipython \
        ptpython \
        tabulate \
	' \
    && apt-get update \
    && apt-get install -y --no-install-recommends $deps $buildDeps \
    && git clone https://github.com/yyuu/pyenv.git .pyenv \
    && for pyversion in ${PYTHON_VERSIONS}; \
        do \
            pyenv install ${pyversion} \
            && pyenv local ${pyversion} \
            && pip install ${requiredPipPackages}; \
        done \
    && pyenv global ${PYTHON_VERSIONS} \
    && find /usr/local \
		\( -type d -a -name test -o -name tests \) \
		-o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
		-exec rm -rf '{}' + \
    && rm -rf /tmp/python-build* \
	&& apt-get purge -y --auto-remove $buildDeps

# Define env variables
ENV ROOT=/data
ENV PYTHONUNBUFFERED=1 \
    CONFSRC=./conf \
    CONFDIR=${ROOT}/conf \
    SRCDIR=${ROOT}/src \
    TOXFILEDIR=${ROOT}/src \
    DEPLOYMENTDIR=${ROOT}/deployment \
    SCRIPTSSRC=./scripts \
    SCRIPTSDIR=${ROOT}/scripts \
    BUILDDEPSFILE=builddeps.txt \
    DEPSFILE=deps.txt \
    PIPSRC=/pip
ENV PYTHONPATH $PIPSRC:$SRCDIR:$PYTHONPATH

# make directories
RUN mkdir -p ${SRCDIR} && \
    mkdir -p ${DEPLOYMENTDIR} && \
    mkdir -p ${SCRIPTSDIR} && \
    mkdir -p /root/.ptpython

RUN chown -R www-data ${ROOT}

COPY ${CONFSRC} ${CONFDIR}
COPY ${SCRIPTSSRC} ${SCRIPTSDIR}
COPY docker-entrypoint.py /usr/local/bin/runscript

RUN ln -s ${CONFDIR}/pip.conf /etc/pip.conf

# set workdir
WORKDIR ${SRCDIR}

# set run command
ENTRYPOINT ["runscript"]
CMD ["help"]
